version: '3.9'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.10
    ports:
      - "2181:2181"
    restart: unless-stopped
    networks:
      - network
    healthcheck:
      test: [ "CMD", "nc", "-vz", "localhost", "2181" ]
      interval: 5s
      timeout: 10s
      retries: 5
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:6.2.10
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "29092:29092"
    restart: unless-stopped
    networks:
      - network
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "29092"]
      interval: 5s
      timeout: 10s
      retries: 5
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  rabitmq:
    image: rabbitmq:3.11.13-management-alpine
    ports:
      # AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
    restart: unless-stopped
    networks:
      - network
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    restart: unless-stopped
    networks:
      - network

  activemq:
    image: quay.io/artemiscloud/activemq-artemis-broker:1.0.17
    ports:
      - "8161:8161"
      - "61616:61616"
    restart: unless-stopped
    networks:
      network:
        ipv4_address: 10.5.0.5
    environment:
      - AMQ_USER=user
      - AMQ_PASSWORD=password


networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1