CREATE TABLE user (
  id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  email VARCHAR(255) NOT NULL,
  age SMALLINT NOT NULL,
  gender VARCHAR(25)
);